### ISSUE TITLE
Make releases

### ISSUE THREAD

**Issue by uggedal** [seanpringle/xoat#2]
I'm going to package xoat for [Void Linux](http://voidlinux.eu).

It would be great if you could start cutting releases at stable points in the development. `git tag` would suffice. Bonus points for using semver.

**Comment by seanpringle** [comment]
This seems kind of meaningless :) I'm not doing any sort of formal development cycle, have no specific aims for major or minor milestones, am not doing any QA (just eating my own dog food). Any tags would be arbitrary and no more relevant than a commit hash or time stamp.

    git archive -o xoat.$(date +'%Y%m%d').zip 7ae527002bee2905096487ddf74386e0159051b2

Convince me otherwise?

**Comment by uggedal** [comment]
Sounds fair.
